Vichalana Anomaly Benchmark. In this dataset, the numbers of disk and jvm samples are 1/6 of other samples. So, we use cpu, mem, and network data. Because we don't use disk data, so we will ignore the type 3 and type 4 (scenario 03, 04, 05, 09) data.

In [1]:
import pandas as pd
scenarios = [1,2,6,7,8,10,11]
#scenarios = [1]
names = ['cpu', 'memory', 'network_io']
all_data = pd.DataFrame()
for name in names:
    labels = []
    sce_data = pd.DataFrame()
    for sce in scenarios:
        if sce != 11:
            normal_data = pd.read_csv('./normal_datasets/part_'+str(sce)+'/'+name+'_parameters.csv')
            sce_data = pd.concat([sce_data, normal_data], ignore_index=True)
            abnormal_data = pd.read_csv('./anomalous_datasets/scenario_'+str(sce)+'/'+name +'_parameters.csv')
            sce_data = pd.concat([sce_data, abnormal_data], ignore_index=True)
            labels += [0]*len(normal_data)
            labels += [1]*len(abnormal_data)
        else:
            normal_data = pd.read_csv('./normal_datasets/part_'+str(sce)+'/'+name+'_parameters.csv')
            sce_data = pd.concat([sce_data, normal_data], ignore_index=True)
            labels += [0]*len(normal_data)
    if name == 'cpu':
        all_data = pd.concat([all_data, sce_data], axis=1)
    else:
        all_data = pd.concat([all_data, sce_data.iloc[:,1:]], axis=1)
all_data

,@timestamp,system.cpu.user.pct,system.cpu.system.pct,system.cpu.idle.pct,system.cpu.iowait.pct,system.cpu.softirq.pct,system.cpu.total.pct,system.memory.used.pct,system.network.in.bytes,system.network.in.packets,system.network.in.dropped,system.network.out.bytes,system.network.out.packets,system.network.out.errors
0,2018-01-01 00:00:00,0.7110,0.0675,3.1702,0.0302,0.0211,0.8298,0.8429,3000000.0,13038,1,3000000.0,12179,0
1,2018-01-01 00:00:10,0.6695,0.0633,3.2410,0.0101,0.0161,0.7590,0.8471,3000000.0,13178,1,4000000.0,12232,0
2,2018-01-01 00:00:20,0.5851,0.0755,3.3162,0.0020,0.0211,0.6838,0.8489,4000000.0,12945,1,3000000.0,12161,0
3,2018-01-01 00:00:30,0.5350,0.0836,3.3552,0.0050,0.0212,0.6448,0.8547,3000000.0,13850,1,3000000.0,12750,0
4,2018-01-01 00:00:40,0.6239,0.0584,3.2926,0.0040,0.0211,0.7074,0.8558,3000000.0,12838,0,4000000.0,11985,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45481,2018-01-01 16:31:10,0.2491,0.0472,3.6916,0.0030,0.0090,0.3084,0.9683,4000000.0,6924,1,4000000.0,7347,7
45482,2018-01-01 16:31:20,0.2162,0.0535,3.7182,0.0030,0.0091,0.2818,0.9683,3000000.0,7967,0,4000000.0,8275,7
45483,2018-01-01 16:31:30,0.2237,0.0582,3.7020,0.0050,0.0110,0.2980,0.9685,4000000.0,6603,1,4000000.0,7238,2
45484,2018-01-01 16:31:40,0.2142,0.0515,3.7211,0.0051,0.0081,0.2789,0.9686,4000000.0,6934,1,4000000.0,7315,9
45485,2018-01-01 16:31:50,0.3366,0.0643,3.5800,0.0040,0.0151,0.4200,0.9658,4000000.0,8835,0,3000000.0,9187,1

In [2]:
train_data = all_data.iloc[:,1:]
train_data

,system.cpu.user.pct,system.cpu.system.pct,system.cpu.idle.pct,system.cpu.iowait.pct,system.cpu.softirq.pct,system.cpu.total.pct,system.memory.used.pct,system.network.in.bytes,system.network.in.packets,system.network.in.dropped,system.network.out.bytes,system.network.out.packets,system.network.out.errors
0,0.7110,0.0675,3.1702,0.0302,0.0211,0.8298,0.8429,3000000.0,13038,1,3000000.0,12179,0
1,0.6695,0.0633,3.2410,0.0101,0.0161,0.7590,0.8471,3000000.0,13178,1,4000000.0,12232,0
2,0.5851,0.0755,3.3162,0.0020,0.0211,0.6838,0.8489,4000000.0,12945,1,3000000.0,12161,0
3,0.5350,0.0836,3.3552,0.0050,0.0212,0.6448,0.8547,3000000.0,13850,1,3000000.0,12750,0
4,0.6239,0.0584,3.2926,0.0040,0.0211,0.7074,0.8558,3000000.0,12838,0,4000000.0,11985,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45481,0.2491,0.0472,3.6916,0.0030,0.0090,0.3084,0.9683,4000000.0,6924,1,4000000.0,7347,7
45482,0.2162,0.0535,3.7182,0.0030,0.0091,0.2818,0.9683,3000000.0,7967,0,4000000.0,8275,7
45483,0.2237,0.0582,3.7020,0.0050,0.0110,0.2980,0.9685,4000000.0,6603,1,4000000.0,7238,2
45484,0.2142,0.0515,3.7211,0.0051,0.0081,0.2789,0.9686,4000000.0,6934,1,4000000.0,7315,9
45485,0.3366,0.0643,3.5800,0.0040,0.0151,0.4200,0.9658,4000000.0,8835,0,3000000.0,9187,1

In [3]:
labels = pd.DataFrame(labels, columns=['label'])
test_data_label = labels
test_data_label

       label
0          0
1          0
2          0
3          0
4          0
...      ...
45481      0
45482      0
45483      0
45484      0
45485      0

[45486 rows x 1 columns]

In [4]:
len(test_data_label[test_data_label.label == 1])/len(test_data_label)

0.06450336367233875

In [5]:
all_label_data = pd.concat([labels, train_data], axis=1)
all_label_data

,label,system.cpu.user.pct,system.cpu.system.pct,system.cpu.idle.pct,system.cpu.iowait.pct,system.cpu.softirq.pct,system.cpu.total.pct,system.memory.used.pct,system.network.in.bytes,system.network.in.packets,system.network.in.dropped,system.network.out.bytes,system.network.out.packets,system.network.out.errors
0,0,0.7110,0.0675,3.1702,0.0302,0.0211,0.8298,0.8429,3000000.0,13038,1,3000000.0,12179,0
1,0,0.6695,0.0633,3.2410,0.0101,0.0161,0.7590,0.8471,3000000.0,13178,1,4000000.0,12232,0
2,0,0.5851,0.0755,3.3162,0.0020,0.0211,0.6838,0.8489,4000000.0,12945,1,3000000.0,12161,0
3,0,0.5350,0.0836,3.3552,0.0050,0.0212,0.6448,0.8547,3000000.0,13850,1,3000000.0,12750,0
4,0,0.6239,0.0584,3.2926,0.0040,0.0211,0.7074,0.8558,3000000.0,12838,0,4000000.0,11985,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45481,0,0.2491,0.0472,3.6916,0.0030,0.0090,0.3084,0.9683,4000000.0,6924,1,4000000.0,7347,7
45482,0,0.2162,0.0535,3.7182,0.0030,0.0091,0.2818,0.9683,3000000.0,7967,0,4000000.0,8275,7
45483,0,0.2237,0.0582,3.7020,0.0050,0.0110,0.2980,0.9685,4000000.0,6603,1,4000000.0,7238,2
45484,0,0.2142,0.0515,3.7211,0.0051,0.0081,0.2789,0.9686,4000000.0,6934,1,4000000.0,7315,9
45485,0,0.3366,0.0643,3.5800,0.0040,0.0151,0.4200,0.9658,4000000.0,8835,0,3000000.0,9187,1

In [6]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
#normalized_train_data = pd.DataFrame(scaler.fit_transform(train_data))
normalized_test_data = pd.DataFrame(scaler.fit_transform(train_data))
normalized_test_data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.145065,0.052808,0.839834,0.029801,0.696370,0.160166,0.251708,0.333333,0.863835,0.142857,0.500000,0.877829,0.00
1,0.133912,0.049370,0.858825,0.009966,0.531353,0.141175,0.275626,0.333333,0.873112,0.142857,0.666667,0.881649,0.00
2,0.111231,0.059358,0.878997,0.001974,0.696370,0.121003,0.285877,0.444444,0.857673,0.142857,0.500000,0.876532,0.00
3,0.097767,0.065990,0.889458,0.004934,0.699670,0.110542,0.318907,0.333333,0.917638,0.142857,0.500000,0.918985,0.00
4,0.121658,0.045358,0.872666,0.003947,0.696370,0.127334,0.325171,0.333333,0.850583,0.000000,0.666667,0.863846,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45481,0.020935,0.036188,0.979694,0.002960,0.297030,0.020306,0.965831,0.444444,0.458720,0.142857,0.666667,0.529552,0.28
45482,0.012093,0.041346,0.986829,0.002960,0.300330,0.013171,0.965831,0.333333,0.527829,0.000000,0.666667,0.596439,0.28
45483,0.014109,0.045194,0.982484,0.004934,0.363036,0.017516,0.966970,0.444444,0.437450,0.142857,0.666667,0.521695,0.08
45484,0.011556,0.039709,0.987607,0.005033,0.267327,0.012393,0.967540,0.444444,0.459382,0.142857,0.666667,0.527245,0.36
45485,0.044449,0.050188,0.949759,0.003947,0.498350,0.050241,0.951595,0.444444,0.585343,0.000000,0.500000,0.662174,0.04

In [7]:
import numpy as np
from sklearn.decomposition import PCA

pca = PCA(n_components=6)
#pca_train_data = pca.fit_transform(normalized_train_data)
pca_test_data = pca.fit_transform(normalized_test_data)

print(pca.explained_variance_ratio_)
print(sum(pca.explained_variance_ratio_))
print(pca.singular_values_)

[0.46895787 0.16285295 0.10883544 0.0843251  0.07487702 0.0511416 ]
0.9509899744356801
[61.08442294 35.99659062 29.4271855  25.90251847 24.40831699 20.17208076]

## Base learner

In [8]:
from __future__ import division
from __future__ import print_function

import os
import sys
from time import time

# temporary solution for relative imports in case pyod is not installed
# if pyod is installed, no need to use the following line
sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname("__file__"), '..')))
# supress warnings for clean output
import warnings

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from scipy.io import loadmat

from pyod.models.abod import ABOD
from pyod.models.cblof import CBLOF
from pyod.models.feature_bagging import FeatureBagging
from pyod.models.hbos import HBOS
from pyod.models.iforest import IForest
from pyod.models.knn import KNN
from pyod.models.lof import LOF
from pyod.models.mcd import MCD
from pyod.models.ocsvm import OCSVM
from pyod.models.pca import PCA

from pyod.utils.utility import standardizer
from pyod.utils.utility import precision_n_scores
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn import metrics

In [9]:
def pred_labels(y_test, test_scores):
    fpr, tpr, thresholds = roc_curve(y_test, test_scores)
    cutoff = thresholds[np.argmax(tpr - fpr)]
    pred_label = []
    for each in test_scores:
        if each > cutoff:
            pred_label.append(1)
        else:
            pred_label.append(0)    
    return pred_label

In [10]:
# X_train = normalized_test_data
# X_test = normalized_test_data
X_train = pca_test_data
X_test = pca_test_data
y_train = test_data_label
y_test = test_data_label

In [11]:
def base_models():
    # Define nine outlier detection tools to be compared
    random_state = np.random.RandomState(42)

    #df_columns = ['Data', '#Samples', '# Dimensions', 'Outlier Perc',
    #              'ABOD', 'CBLOF', 'HBOS', 'IForest', 'KNN', 'LOF', 'MCD',
    #              'OCSVM']
    df_columns = ['Data', '#Samples', '# Dimensions', 'Outlier Perc',
                  'IForest', 'KNN', 'LOF', 'OCSVM']

    pr_df = pd.DataFrame(columns=df_columns)
    re_df = pd.DataFrame(columns=df_columns)
    f1_df = pd.DataFrame(columns=df_columns)
    roc_df = pd.DataFrame(columns=df_columns)
    train_time_df = pd.DataFrame(columns=df_columns)
    test_time_df = pd.DataFrame(columns=df_columns)
    label_df = pd.DataFrame(columns=df_columns[4:])

    outliers_fraction = np.count_nonzero(y_train) / len(y_train)
    outliers_percentage = round(outliers_fraction * 100, ndigits=4)

    # construct containers for saving results
    pr_list = ['Monitor_data', X_train.shape[0], X_train.shape[1], outliers_percentage]
    re_list = ['Monitor_data', X_train.shape[0], X_train.shape[1], outliers_percentage]
    f1_list = ['Monitor_data', X_train.shape[0], X_train.shape[1], outliers_percentage]
    roc_list = ['Monitor_data', X_train.shape[0], X_train.shape[1], outliers_percentage]
    train_time_list = ['Monitor_data', X_train.shape[0], X_train.shape[1], outliers_percentage]
    test_time_list = ['Monitor_data', X_train.shape[0], X_train.shape[1], outliers_percentage]
    label_list = []

    classifiers = {
        #'Angle-based Outlier Detector (ABOD)': ABOD(
        #    contamination=outliers_fraction),
        #    'Cluster-based Local Outlier Factor': CBLOF(
        #        contamination=outliers_fraction, check_estimator=False,
        #        random_state=random_state),
        #    'Histogram-base Outlier Detection (HBOS)': HBOS(
        #        contamination=outliers_fraction),
            'Isolation Forest': IForest(contamination=outliers_fraction,
                                        random_state=random_state),
            'K Nearest Neighbors (KNN)': KNN(contamination=outliers_fraction),
            'Local Outlier Factor (LOF)': LOF(
                contamination=outliers_fraction),
        #   'Minimum Covariance Determinant (MCD)': MCD(
        #        contamination=outliers_fraction, random_state=random_state),
            'One-class SVM (OCSVM)': OCSVM(contamination=outliers_fraction),
            #'Principal Component Analysis (PCA)': PCA(
            #    contamination=outliers_fraction, random_state=random_state),
        }

    for clf_name, clf in classifiers.items():
        t0 = time()
        clf.fit(X_train)
        t1 = time()
        test_scores = clf.decision_function(X_test)
        t2 = time()
        mean_score = np.nanmean(test_scores)
        test_scores[np.isnan(test_scores)] = mean_score
        train_duration = round(t1 - t0, ndigits=4)
        test_duration = round(t2-t1, ndigits=4)
        train_time_list.append(train_duration)
        test_time_list.append(test_duration)
        #print(test_scores.tolist())
        pred_label = pred_labels(y_test, test_scores)
        pr = round(metrics.precision_score(y_test, pred_label, average='macro'), ndigits=4)
        re = round(metrics.recall_score(y_test, pred_label, average='macro'), ndigits=4)
        f1 = round(f1_score(y_test, pred_label, average='macro'), ndigits=4)
        roc = round(roc_auc_score(y_test, test_scores), ndigits=4)
        print('{clf_name} ROC:{roc}, f1 score:{f1}, '
              'execution time: {duration}s'.format(clf_name=clf_name, roc=roc, f1=f1, duration=train_duration))

        pr_list.append(pr)
        re_list.append(re)
        f1_list.append(f1)
        roc_list.append(roc)
        label_list.append(pred_label)

    temp_df = pd.DataFrame(train_time_list).transpose()
    temp_df.columns = df_columns
    train_time_df = pd.concat([train_time_df, temp_df], axis=0)
    
    temp_df = pd.DataFrame(test_time_list).transpose()
    temp_df.columns = df_columns
    test_time_df = pd.concat([test_time_df, temp_df], axis=0)

    temp_df = pd.DataFrame(roc_list).transpose()
    temp_df.columns = df_columns
    roc_df = pd.concat([roc_df, temp_df], axis=0)

    temp_df = pd.DataFrame(f1_list).transpose()
    temp_df.columns = df_columns
    f1_df = pd.concat([f1_df, temp_df], axis=0)

    temp_df = pd.DataFrame(label_list).transpose()
    temp_df.columns = df_columns[4:]
    label_df = pd.concat([label_df, temp_df], axis=0)

    temp_df = pd.DataFrame(pr_list).transpose()
    temp_df.columns = df_columns
    pr_df = pd.concat([pr_df, temp_df], axis=0)

    temp_df = pd.DataFrame(re_list).transpose()
    temp_df.columns = df_columns
    re_df = pd.concat([re_df, temp_df], axis=0)
    return train_time_df, test_time_df, pr_df, re_df, f1_df, roc_df

In [12]:
df_columns = ['Data', '#Samples', '# Dimensions', 'Outlier Perc',
              'IForest', 'KNN', 'LOF', 'OCSVM']
t_pr_df = pd.DataFrame(columns=df_columns)
t_re_df = pd.DataFrame(columns=df_columns)
t_f1_df = pd.DataFrame(columns=df_columns)
t_roc_df = pd.DataFrame(columns=df_columns)
t_train_time_df = pd.DataFrame(columns=df_columns)
t_test_time_df = pd.DataFrame(columns=df_columns)

for i in range(10):
    print(i)
    train_time_e, test_time_e, pr_e, re_e, f1_e, roc_e = base_models()
    t_pr_df = pd.concat([t_pr_df, pr_e], axis=0, ignore_index=True)
    t_re_df = pd.concat([t_re_df, re_e], axis=0, ignore_index=True)
    t_f1_df = pd.concat([t_f1_df, f1_e], axis=0, ignore_index=True)
    t_roc_df = pd.concat([t_roc_df, roc_e], axis=0, ignore_index=True)
    t_train_time_df = pd.concat([t_train_time_df, train_time_e], axis=0, ignore_index=True)
    t_test_time_df = pd.concat([t_test_time_df, test_time_e], axis=0, ignore_index=True)

0
Isolation Forest ROC:0.9018, f1 score:0.658, execution time: 2.3008s
K Nearest Neighbors (KNN) ROC:0.7049, f1 score:0.5519, execution time: 0.9001s
Local Outlier Factor (LOF) ROC:0.5643, f1 score:0.5128, execution time: 1.5194s
One-class SVM (OCSVM) ROC:0.8931, f1 score:0.6778, execution time: 208.364s
1
Isolation Forest ROC:0.9018, f1 score:0.658, execution time: 2.0247s
K Nearest Neighbors (KNN) ROC:0.7049, f1 score:0.5519, execution time: 0.8131s
Local Outlier Factor (LOF) ROC:0.5643, f1 score:0.5128, execution time: 1.5282s
One-class SVM (OCSVM) ROC:0.8931, f1 score:0.6778, execution time: 207.3744s
2
Isolation Forest ROC:0.9018, f1 score:0.658, execution time: 2.1196s
K Nearest Neighbors (KNN) ROC:0.7049, f1 score:0.5519, execution time: 0.8391s
Local Outlier Factor (LOF) ROC:0.5643, f1 score:0.5128, execution time: 1.5848s
One-class SVM (OCSVM) ROC:0.8931, f1 score:0.6778, execution time: 199.7588s
3
Isolation Forest ROC:0.9018, f1 score:0.658, execution time: 2.1774s
K Nearest Neighbors (KNN) ROC:0.7049, f1 score:0.5519, execution time: 0.8683s
Local Outlier Factor (LOF) ROC:0.5643, f1 score:0.5128, execution time: 1.5836s
One-class SVM (OCSVM) ROC:0.8931, f1 score:0.6778, execution time: 263.3027s
4
Isolation Forest ROC:0.9018, f1 score:0.658, execution time: 2.1038s
K Nearest Neighbors (KNN) ROC:0.7049, f1 score:0.5519, execution time: 0.946s
Local Outlier Factor (LOF) ROC:0.5643, f1 score:0.5128, execution time: 1.5318s
One-class SVM (OCSVM) ROC:0.8931, f1 score:0.6778, execution time: 217.1537s
5
Isolation Forest ROC:0.9018, f1 score:0.658, execution time: 1.9134s
K Nearest Neighbors (KNN) ROC:0.7049, f1 score:0.5519, execution time: 0.7549s
Local Outlier Factor (LOF) ROC:0.5643, f1 score:0.5128, execution time: 1.4201s
One-class SVM (OCSVM) ROC:0.8931, f1 score:0.6778, execution time: 182.7089s
6
Isolation Forest ROC:0.9018, f1 score:0.658, execution time: 1.9197s
K Nearest Neighbors (KNN) ROC:0.7049, f1 score:0.5519, execution time: 0.757s
Local Outlier Factor (LOF) ROC:0.5643, f1 score:0.5128, execution time: 1.4092s
One-class SVM (OCSVM) ROC:0.8931, f1 score:0.6778, execution time: 183.3552s
7
Isolation Forest ROC:0.9018, f1 score:0.658, execution time: 2.0529s
K Nearest Neighbors (KNN) ROC:0.7049, f1 score:0.5519, execution time: 0.8522s
Local Outlier Factor (LOF) ROC:0.5643, f1 score:0.5128, execution time: 1.5195s
One-class SVM (OCSVM) ROC:0.8931, f1 score:0.6778, execution time: 207.1933s
8
Isolation Forest ROC:0.9018, f1 score:0.658, execution time: 2.0517s
K Nearest Neighbors (KNN) ROC:0.7049, f1 score:0.5519, execution time: 0.8093s
Local Outlier Factor (LOF) ROC:0.5643, f1 score:0.5128, execution time: 1.4799s
One-class SVM (OCSVM) ROC:0.8931, f1 score:0.6778, execution time: 198.8964s
9
Isolation Forest ROC:0.9018, f1 score:0.658, execution time: 1.8866s
K Nearest Neighbors (KNN) ROC:0.7049, f1 score:0.5519, execution time: 0.7245s
Local Outlier Factor (LOF) ROC:0.5643, f1 score:0.5128, execution time: 1.3273s
One-class SVM (OCSVM) ROC:0.8931, f1 score:0.6778, execution time: 195.4983s

In [13]:
print('Train time complexity')
learner = ['IForest', 'KNN', 'LOF', 'OCSVM']
mean_train_time = []
std_train_time = []
for each in learner:
    mean_train_time.append(round(t_train_time_df[each].mean(), ndigits=4))
    std_train_time.append(round(t_train_time_df[each].std(), ndigits=4))
print(mean_train_time)
print(std_train_time)
t_train_time_df

Train time complexity
[2.0551, 0.8264, 1.4904, 206.3606]
[0.1289, 0.0692, 0.0821, 22.7805]

,Data,#Samples,# Dimensions,Outlier Perc,IForest,KNN,LOF,OCSVM
0,Monitor_data,45486,6,6.4503,2.3008,0.9001,1.5194,208.364
1,Monitor_data,45486,6,6.4503,2.0247,0.8131,1.5282,207.3744
2,Monitor_data,45486,6,6.4503,2.1196,0.8391,1.5848,199.7588
3,Monitor_data,45486,6,6.4503,2.1774,0.8683,1.5836,263.3027
4,Monitor_data,45486,6,6.4503,2.1038,0.946,1.5318,217.1537
5,Monitor_data,45486,6,6.4503,1.9134,0.7549,1.4201,182.7089
6,Monitor_data,45486,6,6.4503,1.9197,0.757,1.4092,183.3552
7,Monitor_data,45486,6,6.4503,2.0529,0.8522,1.5195,207.1933
8,Monitor_data,45486,6,6.4503,2.0517,0.8093,1.4799,198.8964
9,Monitor_data,45486,6,6.4503,1.8866,0.7245,1.3273,195.4983

In [14]:
print('Test time complexity')
learner = ['IForest', 'KNN', 'LOF', 'OCSVM']
mean_test_time = []
std_test_time = []
for each in learner:
    mean_test_time.append(round(t_test_time_df[each].mean(), ndigits=4))
    std_test_time.append(round(t_test_time_df[each].std(), ndigits=4))
print(mean_test_time)
print(std_test_time)
t_test_time_df

Test time complexity
[0.8088, 3.7896, 1.424, 96.447]
[0.0376, 0.2616, 0.1102, 6.5647]

,Data,#Samples,# Dimensions,Outlier Perc,IForest,KNN,LOF,OCSVM
0,Monitor_data,45486,6,6.4503,0.8361,3.9057,1.3843,104.9483
1,Monitor_data,45486,6,6.4503,0.8039,3.883,1.442,101.0079
2,Monitor_data,45486,6,6.4503,0.8477,4.0008,1.4982,99.2229
3,Monitor_data,45486,6,6.4503,0.8683,4.0082,1.4376,106.5465
4,Monitor_data,45486,6,6.4503,0.8196,4.129,1.407,89.6493
5,Monitor_data,45486,6,6.4503,0.7652,3.5382,1.3332,89.9125
6,Monitor_data,45486,6,6.4503,0.7689,3.5273,1.3242,97.0705
7,Monitor_data,45486,6,6.4503,0.8168,3.8774,1.4345,95.5709
8,Monitor_data,45486,6,6.4503,0.8098,3.7296,1.6825,87.211
9,Monitor_data,45486,6,6.4503,0.7522,3.2968,1.2967,93.3304

In [15]:
print('ROC Performance')
learner = ['IForest', 'KNN', 'LOF', 'OCSVM']
mean_roc = []
for each in learner:
    mean_roc.append(round(t_roc_df[each].mean(), ndigits=4))
print(mean_roc)
t_roc_df

ROC Performance
[0.9018, 0.7049, 0.5643, 0.8931]

,Data,#Samples,# Dimensions,Outlier Perc,IForest,KNN,LOF,OCSVM
0,Monitor_data,45486,6,6.4503,0.9018,0.7049,0.5643,0.8931
1,Monitor_data,45486,6,6.4503,0.9018,0.7049,0.5643,0.8931
2,Monitor_data,45486,6,6.4503,0.9018,0.7049,0.5643,0.8931
3,Monitor_data,45486,6,6.4503,0.9018,0.7049,0.5643,0.8931
4,Monitor_data,45486,6,6.4503,0.9018,0.7049,0.5643,0.8931
5,Monitor_data,45486,6,6.4503,0.9018,0.7049,0.5643,0.8931
6,Monitor_data,45486,6,6.4503,0.9018,0.7049,0.5643,0.8931
7,Monitor_data,45486,6,6.4503,0.9018,0.7049,0.5643,0.8931
8,Monitor_data,45486,6,6.4503,0.9018,0.7049,0.5643,0.8931
9,Monitor_data,45486,6,6.4503,0.9018,0.7049,0.5643,0.8931

In [16]:
print('Precision')
learner = ['IForest', 'KNN', 'LOF', 'OCSVM']
mean_pr = []
for each in learner:
    mean_pr.append(round(t_pr_df[each].mean(), ndigits=4))
print(mean_pr)
t_pr_df

Precision
[0.6279, 0.559, 0.5249, 0.6408]

,Data,#Samples,# Dimensions,Outlier Perc,IForest,KNN,LOF,OCSVM
0,Monitor_data,45486,6,6.4503,0.6279,0.559,0.5249,0.6408
1,Monitor_data,45486,6,6.4503,0.6279,0.559,0.5249,0.6408
2,Monitor_data,45486,6,6.4503,0.6279,0.559,0.5249,0.6408
3,Monitor_data,45486,6,6.4503,0.6279,0.559,0.5249,0.6408
4,Monitor_data,45486,6,6.4503,0.6279,0.559,0.5249,0.6408
5,Monitor_data,45486,6,6.4503,0.6279,0.559,0.5249,0.6408
6,Monitor_data,45486,6,6.4503,0.6279,0.559,0.5249,0.6408
7,Monitor_data,45486,6,6.4503,0.6279,0.559,0.5249,0.6408
8,Monitor_data,45486,6,6.4503,0.6279,0.559,0.5249,0.6408
9,Monitor_data,45486,6,6.4503,0.6279,0.559,0.5249,0.6408

In [17]:
print('Recall')
learner = ['IForest', 'KNN', 'LOF', 'OCSVM']
mean_re = []
for each in learner:
    mean_re.append(round(t_re_df[each].mean(), ndigits=4))
print(mean_re)
t_re_df

Recall
[0.8428, 0.6817, 0.5681, 0.8525]

,Data,#Samples,# Dimensions,Outlier Perc,IForest,KNN,LOF,OCSVM
0,Monitor_data,45486,6,6.4503,0.8428,0.6817,0.5681,0.8525
1,Monitor_data,45486,6,6.4503,0.8428,0.6817,0.5681,0.8525
2,Monitor_data,45486,6,6.4503,0.8428,0.6817,0.5681,0.8525
3,Monitor_data,45486,6,6.4503,0.8428,0.6817,0.5681,0.8525
4,Monitor_data,45486,6,6.4503,0.8428,0.6817,0.5681,0.8525
5,Monitor_data,45486,6,6.4503,0.8428,0.6817,0.5681,0.8525
6,Monitor_data,45486,6,6.4503,0.8428,0.6817,0.5681,0.8525
7,Monitor_data,45486,6,6.4503,0.8428,0.6817,0.5681,0.8525
8,Monitor_data,45486,6,6.4503,0.8428,0.6817,0.5681,0.8525
9,Monitor_data,45486,6,6.4503,0.8428,0.6817,0.5681,0.8525

In [18]:
print('F1 score')
learner = ['IForest', 'KNN', 'LOF', 'OCSVM']
mean_f1 = []
for each in learner:
    mean_f1.append(round(t_f1_df[each].mean(), ndigits=4))
print(mean_f1)
t_f1_df

F1 score
[0.658, 0.5519, 0.5128, 0.6778]

,Data,#Samples,# Dimensions,Outlier Perc,IForest,KNN,LOF,OCSVM
0,Monitor_data,45486,6,6.4503,0.658,0.5519,0.5128,0.6778
1,Monitor_data,45486,6,6.4503,0.658,0.5519,0.5128,0.6778
2,Monitor_data,45486,6,6.4503,0.658,0.5519,0.5128,0.6778
3,Monitor_data,45486,6,6.4503,0.658,0.5519,0.5128,0.6778
4,Monitor_data,45486,6,6.4503,0.658,0.5519,0.5128,0.6778
5,Monitor_data,45486,6,6.4503,0.658,0.5519,0.5128,0.6778
6,Monitor_data,45486,6,6.4503,0.658,0.5519,0.5128,0.6778
7,Monitor_data,45486,6,6.4503,0.658,0.5519,0.5128,0.6778
8,Monitor_data,45486,6,6.4503,0.658,0.5519,0.5128,0.6778
9,Monitor_data,45486,6,6.4503,0.658,0.5519,0.5128,0.6778